config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'

  resources :articles

#-----------admin後台--------------
  namespace :admin do
    resources :articles do
      member do
        patch :move_up
        patch :move_down
        post :publish
        post :hide
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_list
  belongs_to :user



  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles

  def admin?
    is_admin
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  before_action :find_article, except: [:index, :new, :create]
  layout "admin"

  # ---CRUD---

  def index
    @articles = Article.all.order("position ASC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to admin_articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
      redirect_to admin_articles_path
  end


  def publish
    @article.publish!
    redirect_to admin_articles_path
  end

  def hide
    @article.hide!
    redirect_to admin_articles_path
  end

  def move_up
    @article.move_higher
    redirect_to admin_articles_path
  end

  def move_down
    @article.move_lower
    redirect_to admin_articles_path
  end




  # ---private---

  private

  def find_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :content,:summary, :user_id, :image, :is_hidden)
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, expect: [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]


  def index
    @articles = Article.where(:is_hidden => false).order("position ASC")
  end

  def show
    @user = @article.user
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
      redirect_to articles_path
  end


  def publish
    @article = Article.find(params[:id])
    @article.publish!
    redirect_to :back
  end

  def hide
    @article = Article.find(params[:id])
    @article.hide!
    redirect_to :back
  end




  private

  def find_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :content,:summary, :user_id, :image, :is_hidden)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article] do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "標題" %>
    <% if @article.image.present? %>
      <span>首圖</span> <br>
      <%= image_tag(@article.image.thumb.url) %>
    <% end %>

    <%= f.input :image, as: :file ,:label => "首圖" %>
    <%= f.input :summary, :label => "摘要" %>
    <%= f.input :content, as: :wysihtml5,:label => "内容" %>
    <%= f.input :is_hidden, :label => "隱藏" %>

    <hr>

  </div>
  <%= f.submit "提交", class: "btn btn-sm btn-default", data: {disable_with: "Submiting..."} %>
<% end %>

app/views/admin/articles/edit.html.erb
<h2>編輯文章</h2>

<%= render "form"%>

app/views/admin/articles/index.html.erb
  <h3 class="text-center">文章列表（Article List）</h3>

  <br>
  <div>
    <%= link_to("增加文章", new_admin_article_path, class: "btn btn-sm btn-default pull-right") %>
  </div>


  <!-- 所有文章列表 -->
  <table class="table table-hover table-bordered table-responsive">
    <thead>
      <tr>
        <td>標題</td>
        <td>作者</td>
        <td>發表時間</td>
        <td>操作</td>
        <td>排序</td>
        <td>公開/隱藏</td>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to(article.title, article) %></td>
          <td><%= article.user.email %></td>
          <td><%= article.created_at %></td>
          <td>
            <%= link_to("Edit", edit_admin_article_path(article)) %> |
            <%= link_to("destroy", admin_article_path(article), method: :delete, data: { confirm: "你确定要删除吗？"}) %>
          </td>
          <td>
            <%= link_to "向上", move_up_admin_article_path(article), method: :patch %> |
            <%= link_to "向下", move_down_admin_article_path(article), method: :patch %>
          </td>
          <td>
            <% if article.is_hidden %>
              <%= link_to publish_admin_article_path(article), method: :post, class: "btn btn-xs btn-success" do %>
              <i class="fa fa-eye"></i><% end %>
            <% else %>
              <%= link_to hide_admin_article_path(article), method: :post, class: "btn btn-xs btn-warning" do %>
              <i class="fa fa-eye-slash"></i><% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "標題" %>
    <% if @article.image.present? %>
      <span>首圖</span> <br>
      <%= image_tag(@article.image.thumb.url) %>
    <% end %>

    <%= f.input :image, as: :file ,:label => "首圖" %>
    <%= f.input :summary, :label => "摘要" %>
    <%= f.input :content, as: :wysihtml5,:label => "内容" %>
    <%= f.input :is_hidden, :label => "隱藏" %>

    <hr>

  </div>
  <%= f.submit "提交", class: "btn btn-sm btn-default", data: {disable_with: "Submiting..."} %>
<% end %>

app/views/articles/edit.html.erb
<h2>編輯文章</h2>

<%= render "form"%>

app/views/articles/index.html.erb
<div class="row">
  <% @articles.each do |article| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to article do %>
        文章標題：<%= article.title %> <br />
        作者： <%= article.user.email %>
        <% if article.image.present? %>
          <%= image_tag(article.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>

    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h2>新增文章</h2>

<%= render "form"%>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">

    <div class="article-show">

      <div class="col-md-8 article-show-box">

        <!-- 標题 -->
        <div class="article-title">
          <h1><%= @article.title %></h1>
        </div>

        <!-- 作者 -->
        <div class="article-author">
          <span> <%= @article.user.email %></span> ·
          <span> <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
        </div>

        <!-- 摘要 -->
        <div class="article-summary">
          <p>
            <blockquote>
                <%= simple_format(@article.summary) %>
            </blockquote>
          </p>
        </div>

        <!-- 主圖 -->
        <div class="article-image">
          <% if @article.image.present? %>
          <%= image_tag(@article.image.thumb.url, class: "thumbnail") %>
          <% end %>
        </div>
        <hr>

        <!-- 内容 -->
        <div class="article-description">
          <%= simple_format(@article.content) %>
        </div>



      </div>

    </div>

  </div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017
        <br>Design by Han

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">WORK </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to("登入", new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <% if current_user.admin? %>
                      <li><%= link_to("管理員後台", admin_articles_path) %></li>
                    <% end %>
                      <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>後台</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content">
      <div class="container">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>

          <div class="">

            <!-- 側邊分類 -->
            <div class="col-md-2 nav-left-style">
              <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
                <hr>
                <li><%= link_to("文章管理", admin_articles_path) %></li>
              </ul>
            </div>

            <!-- 主内容 -->
            <div class="col-md-10">
              <%= yield %>
            </div>

          </div>
      </div>
    </div>


    <%= render "common/footer" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Work</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>